er-coap_src = er-coap.c er-coap-engine.c er-coap-transactions.c      \
  er-coap-observe.c er-coap-separate.c er-coap-res-well-known-core.c \
  er-coap-block1.c er-coap-observe-client.c

# Erbium will implement the REST Engine
CFLAGS += -DREST=coap_rest_implementation

ifeq ($(WITH_DTLS_COAP),1)
CFLAGS += -DWITH_DTLS_COAP=1
er-coap_src += er-coap-dtls.c
else
CFLAGS += -DWITH_DTLS_COAP=0
er-coap_src += er-coap-udp.c
endif
