er-coap_src = er-coap.c er-coap-engine.c er-coap-transactions.c      \
  er-coap-observe.c er-coap-separate.c er-coap-res-well-known-core.c \
  er-coap-block1.c er-coap-observe-client.c

# Erbium will implement the REST Engine
CFLAGS += -DREST=coap_rest_implementation
