#!/bin/sh

MODE=$1
DEV=$2
OS=`uname`

case $MODE in
	raw)
	;;
	
	tap)
	case $OS in
		Linux)
			ifconfig $DEV up
			;;
		Darwin)
			#Sometimes the generated mac address has the translate bit set to 1
			#this conflict with packet filter and sicslow-ethernet
			ifconfig $DEV link 02:a:b:c:d:e
			#IPv6 stack is not always correctly started on tap device
			ip6 -d $DEV
			ip6 -u $DEV
			ifconfig $DEV inet6 up
			;;
		*)
			echo Unknown OS
			;;
	esac
	;;
	
	*)
	echo "Unknown mode $MODE"
	;;
esac

ifconfig $DEV
