#!/bin/sh

DEV=$1
OS=`uname`

if [ "$OS" = "Linux" ]; then
	ifconfig $DEV down
	netstat -nr | awk '{ if ($2 == "'$DEV'") print "route delete -net "$1; }' | sh
elif [ "$OS" = "Darwin" ]; then
	#No action
	:
else
	echo Unknown OS
fi
