#!/bin/sh

MODE=$1
DEV=$2
OS=`uname`

case $MODE in
	raw)
	;;
	
	tap)
	case $OS in
		Linux)
			ifconfig $DEV down
			netstat -nr | awk '{ if ($2 == "'$DEV'") print "route delete -net "$1; }' | sh
			;;
		Darwin)
			#No action
			;;
		*)
			echo Unknown OS
	esac
	;;
	
	*)
	echo "Unknown mode $MODE"
	;;
esac
