CONTIKI_TARGET_DIRS = . dev
# Master clock frequency
MCK=72000000
CFLAGS+=-DAUTOSTART_ENABLE

ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c
endif

CONTIKI_TARGET_SOURCEFILES += $(CONTIKI_TARGET_MAIN)
CONTIKI_TARGET_SOURCEFILES += debug-uart.c newlib.c gqueue.c

include $(CONTIKI)/cpu/arm/stm32f1x_cl/Makefile.stm32f1x_cl

contiki-$(TARGET).a: ${addprefix $(OBJECTDIR)/,symbols.o}

ifndef BASE_IP
BASE_IP := 172.16.1.1
endif

