EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/cc2530dk \
cc2530dk/cc2530dk \
cc2530dk/border-router/cc2530dk \
cc2530dk/udp-ipv6/cc2530dk \
ipv6/multicast/cc2530dk \
sensniff/cc2530dk \

TOOLS=

include ../Makefile.compile-test
