extern const char http_http[8];
extern const char http_200[5];
extern const char http_301[5];
extern const char http_302[5];
extern const char http_get[5];
extern const char http_10[9];
extern const char http_11[9];
extern const char http_content_type[15];
extern const char http_texthtml[10];
extern const char http_location[11];
extern const char http_host[7];
extern const char http_crnl[2];
extern const char http_index_html[12];
extern const char http_404_html[10];
extern const char http_referer[9];
extern const char http_header_200[55];
extern const char http_header_404[62];
extern const char http_content_type_plain[27];
extern const char http_content_type_html[26];
extern const char http_content_type_css [25];
extern const char http_content_type_text[26];
extern const char http_content_type_png [26];
extern const char http_content_type_gif [26];
extern const char http_content_type_jpg [27];
extern const char http_content_type_binary[41];
extern const char http_html[6];
extern const char http_shtml[7];
extern const char http_htm[5];
extern const char http_css[5];
extern const char http_png[5];
extern const char http_gif[5];
extern const char http_jpg[5];
extern const char http_text[6];
extern const char http_txt[5];
