# Platform Makefile

CLEAN += *.jn516x 
CLEAN += *.jn516x.bin
 
include $(CONTIKI)/platform/jn516x/Makefile.common

MODULES += core/net \
           core/net/mac \
           core/net/mac/contikimac \
           core/net/llsec core/net/llsec/noncoresec 
