all: ravenusbstick

#Define CONTIKI_NO_NET=1 for a passthrough ipv6/6lowpan interface using fakeuip.c
#Define UIP_CONF_IPV6=1 to include the uip6 stack (for rpl, internal webserver)
#Do make clean when switching to remove the duplicate library modules
CONTIKI_NO_NET=1
#UIP_CONF_IPV6=1

CONTIKI = ../..

include $(CONTIKI)/Makefile.include
