#define UART0_CONF_BAUD_RATE 38400
#define LPM_CONF_ENABLE 1
#define LPM_CONF_MAX_PM 2
#define NBR_TABLE_CONF_MAX_NEIGHBORS 20
#define UIP_CONF_MAX_ROUTES 40
#define RPL_CONF_LEAF_NODE  1
#define CC2538_CONF_QUIET 1
#define WITH_PHASE_OPTIMIZATION 1