CONTIKI_CPU_DIRS += . init/common

CONTIKI_SOURCEFILES += gdt.c helpers.S idt.c cpu.c

CC       = gcc
LD       = gcc
AS       = as
OBJCOPY  = objcopy
SIZE     = size
STRIP    = strip

CFLAGS  += -Wall -fno-asynchronous-unwind-tables
LDFLAGS += -Wl,-Map=contiki-$(TARGET).map,--build-id=none

ifeq ($(BUILD_RELEASE),1)
	CFLAGS  += -Os -fno-strict-aliasing
	LDFLAGS += -Wl,--strip-all
else
	ifeq ($(findstring clang,$(CC)),clang)
		CFLAGS  += -O0 -g
	else
		CFLAGS  += -Og -ggdb3
	endif
endif
