#/examples/cc2538dk/i2c-example/Makefile

DEFINES=ENERGEST_CONF_ON=1,LPM_CONF_ENABLE=1,LPM_CONF_MAX_PM=2
#CC2538_CONF_QUIET=1	#When released

CONTIKI_PROJECT = i2c-example

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
