#/examples/cc2538dk/i2c-example/Makefile

ENERGEST_CONF_ON=1
#STARTUP_CONF_VERBOSE=0	#When released
#CC2538_CONF_QUIET=1	#When released
LPM_CONF_ENABLE=1
LPM_CONF_MAX_PM=2

CONTIKI_PROJECT = i2c-example

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
