shell_src = shell.c serial-shell.c shell-reboot.c \
            shell-vars.c shell-ps.c shell-rime.c shell-sendtest.c \
            shell-blink.c shell-text.c shell-time.c \
            shell-file.c shell-netfile.c shell-run.c \
            shell-rime-ping.c shell-rime-sniff.c shell-rime-netcmd.c \
            shell-rime-debug.c shell-coffee.c
            #shell-rsh.c
shell_dsc = shell-dsc.c

ifeq ($(TARGET),sky)
	shell_src += shell-sky.c shell-exec.c
endif
