collect-view_src = collect-view.c

ifeq ($(TARGET), sky)
collect-view_src += collect-view-sky.c
else
ifeq ($(TARGET), z1)
collect-view_src += collect-view-z1.c
else
collect-view_src += collect-view-template.c
endif
endif
