CONTIKI_PROJECT = mb851-shell

PROJECTDIRS = $(CONTIKI)/platform/mb851/apps

APPS = serial-shell

PROJECT_SOURCEFILES = shell-sensors.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
