### Add to the source list
BOARD_SOURCEFILES += leds-arch.c

### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Add to the source dirs
CONTIKI_TARGET_DIRS += sensortag/cc1350

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/sensortag/Makefile.sensortag
