# $Id: Makefile.mb851,v 1.1 2010/10/25 09:03:39 salvopitru Exp $


ARCH= irq.c sensors.c acc-sensor.c button-sensor.c temperature-sensor.c mems.c

CONTIKI_TARGET_DIRS = . dev
ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c #contiki-init-net.c
endif

ifdef UIP_CONF_IPV6
CFLAGS += -DWITH_UIP6=1
endif

CONTIKI_TARGET_SOURCEFILES += $(ARCH) $(CONTIKI_TARGET_MAIN)

MCU=STM32W108
include $(CONTIKI)/cpu/stm32w108/Makefile.stm32w108
