TARGET=stepper-robot

all: usbmsctst


CONTIKI=../../..

CONTIKI_TARGET_MAIN=usb-main.c

PROJECT_SOURCEFILES =

USB_MASS_STORAGE_CLASS=1


clean: stepper_robot_clean

.PHONY: stepper_robot_clean

stepper_robot_clean:

include $(CONTIKI)/Makefile.include
