EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/avr-raven \
hello-world/econotag \
hello-world/esb \
hello-world/exp5438 \
hello-world/mb851 \
hello-world/micaz \
hello-world/minimal-net \
hello-world/native \
hello-world/sky \
hello-world/wismote \
hello-world/z1 \
collect/sky \
er-rest-example/sky \
example-shell/native \
netperf/sky \
powertrace/sky \
rime/sky \
rime/z1 \
rime/wismote \
rest-example/sky \
servreg-hack/sky \
sky/sky \
sky-ip/sky \
sky-shell/sky \
sky-shell-exec/sky \
sky-shell-webserver/sky \
telnet-server/minimal-net \
webserver/minimal-net \
webserver-ipv6/sky \
wget/minimal-net \
z1/z1

TOOLS=

include ../Makefile.compile-test
