EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/avr-raven \
hello-world/econotag \
hello-world/esb \
hello-world/exp5438 \
hello-world/mb851 \
hello-world/micaz \
hello-world/minimal-net \
hello-world/native \
hello-world/sky \
hello-world/wismote \
hello-world/z1 \
hello-world/sensinode \
hello-world/cc2530dk \
eeprom-test/native \
ipv6/rpl-border-router/econotag \
collect/sky \
er-rest-example/sky \
er-rest-example/econotag \
example-shell/native \
netperf/sky \
powertrace/sky \
rime/sky \
rime/z1 \
ravenusbstick/avr-ravenusb \
rest-example/sky \
servreg-hack/sky \
sky/sky \
sky-ip/sky \
sky-shell/sky \
sky-shell-exec/sky \
sky-shell-webserver/sky \
telnet-server/minimal-net \
webserver/minimal-net \
webserver-ipv6/sky \
webserver-ipv6/econotag \
wget/minimal-net \
z1/z1 \
settings-example/avr-raven \
sensinode/sensinode \
sensinode/border-router/sensinode \
sensinode/udp-ipv6/sensinode \
sensinode/sniffer/sensinode \
cc2530dk/cc2530dk \
cc2530dk/border-router/cc2530dk \
cc2530dk/udp-ipv6/cc2530dk \
cc2530dk/sniffer/cc2530dk

TOOLS=

include ../Makefile.compile-test
