### List the examples in the directory we want to compile
CONTIKI_PROJECT = 01-hello-world 02-led-and-button 03-timers 04-processes \
                  05-onboard-sensors 06-adc 07-gpio

### When using the "make" command it will compile all examples above
all: $(CONTIKI_PROJECT)

### Location of the Contiki root folder
CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
