CFLAGS += -DBOARD_LAUNCHPAD=1

CONTIKI_TARGET_DIRS += launchpad common

BOARD_SOURCEFILES += board.c launchpad-sensors.c leds-arch.c button-sensor.c
BOARD_SOURCEFILES += ext-flash.c board-spi.c

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
