CONTIKI_SOURCEFILES += rimebuf.c queuebuf.c rimeaddr.c ctimer.c rime.c \
               ibc.c uc.c suc.c ruc.c sibc.c sabc.c abc.c nf.c uabc.c \
               mesh.c route.c \
               tree.c neighbor.c \
               trickle.c
