ifndef CONTIKI
  $(error CONTIKI not defined! You must specify where CONTIKI resides!)
endif

CONTIKI_TARGET_DIRS = . # dev
CONTIKI_TARGET_MAIN = ${addprefix $(OBJECTDIR)/,contiki-main.o}

CONTIKI_TARGET_SOURCEFILES = contiki-main.c clock.c

CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES)

AROPTS=-rc

.SUFFIXES:

### Define the CPU directory
CONTIKI_CPU=$(CONTIKI)/cpu/pic24
include $(CONTIKI)/cpu/pic24/Makefile.pic24

MODULES += core/net/ipv6 core/net core/net/ip 
