# -*- makefile -*-

CONTIKI_TARGET_DIRS = . dev apps net 
CONTIKI_CORE = main
CONTIKI_TARGET_MAIN = ${CONTIKI_CORE}.o

CONTIKI_TARGET_SOURCEFILES += main.c clock.c button-sensor.c button-sensor2.c sensors.c slip.c platform_prints.c

${warning $(CONTIKI)}
CONTIKIMC1322X=$(CONTIKI)/cpu/mc1322x
CONTIKIBOARD=.

CONTIKI_PLAT_DEFS = 

MCU=arm7tdmi-s

include $(CONTIKIMC1322X)/Makefile.mc1322x

MODULES+=core/net \
         core/net/mac \
         core/net/llsec
