EXAMPLESDIR=../..
TOOLSDIR=../../tools

# build avr-rss2 examples, covering IPv6, RPL, Rime, Nullrdc, Contikimac

EXAMPLES = \
examples/avr-rss2/hello-sensors/avr-rss2 \
examples/avr-rss2/ipv6/rpl-udp-report/avr-rss2 \
examples/avr-rss2/ipv6/rpl-border-router/avr-rss2 \
examples/powertrace/avr-rss2 \
examples/rime/avr-rss2
TOOLS=

include ../Makefile.compile-test
