EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

# just compile the Contiki system files and stop when the .a file is ready
EXPLICIT_TARGET=contiki-jn516x.a

# build jn516x examples, covering IPv6, RPL, CoAP, Rime, Nullrdc, Contikimac
EXAMPLES = \
jn516x/dr1175-sensors/jn516x \
jn516x/rime/jn516x \
jn516x/rpl/border-router/jn516x \
jn516x/rpl/node/jn516x \
jn516x/rpl/coap-dongle-node/jn516x \
jn516x/rpl/coap-dr1175-node/jn516x \
jn516x/rpl/coap-dr1199-node/jn516x  

TOOLS=

include ../Makefile.compile-test
