EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

# just compile the Contiki system files and stop when the .a file is ready
EXPLICIT_TARGET=contiki-jn516x.a

# build hello-world (IPv6 and RPL) and contikimac (Rime) examples
EXAMPLES = \
hello-world/jn516x \
jn516x/contikimac/jn516x


TOOLS=

include ../Makefile.compile-test
