# $Id: Makefile,v 1.2 2007/06/28 13:47:28 nvt-se Exp $

all: core
upload: core core.u

core:
	$(MAKE) core.firmware && \
	$(MAKE) core.firmware && \
	$(MAKE) core.firmware

CONTIKI=../..
TARGET=msb430

include $(CONTIKI)/Makefile.include
