erbium_src = er-coap.c er-coap-engine.c er-coap-transactions.c er-coap-observe.c er-coap-separate.c er-coap-res-well-known-core.c

# Erbium will implement the REST Engine
CFLAGS += -DREST=coap_rest_implementation
