CONTIKI=.
-include tools/sky/Makefile

upload-node-%:
	$(MAKE) sky-reset burn-nodeid-$*.upload
	$(MAKE) sky-reset
	sleep 6
	$(MAKE) sky-reset energest-demo.upload

upload-sink: upload-node-41

rundemo:
	java -jar energest.jar /dev/com$(CMOTES)
