CONTIKI_PROJECT = mbxxx-shell

PROJECTDIRS = $(CONTIKI)/platform/mbxxx/apps

APPS = serial-shell

PROJECT_SOURCEFILES = shell-sensors.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
