DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = ubidots-client

APPS = ubidots

CONTIKI_TARGET_SOURCEFILES += sht25.c

all: $(CONTIKI_PROJECT)

WITH_IPV6 = 1

CONTIKI = ../../../..

include $(CONTIKI)/Makefile.include
