# Hey Emacs, this is a -*- makefile -*-

CFLAGS += -I$(MC1322X)/lib/include

# By default, link all objects
LIBOBJS ?= $(patsubst %.c,%.o,$(wildcard $(MC1322X)/lib/*.c))

$(MC1322X)/lib/libmc1322x.a: $(MC1322X)/lib/libmc1322x.a($(LIBOBJS))

ifneq ($(MAKECMDGOALS),clean)
-include $(wildcard $(MC1322X)/lib/*.d)
endif

clean::
	rm -f $(MC1322X)/lib/*.{o,d,a}
