EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/avr-raven \
hello-world/exp5438 \
hello-world/eval-adf7xxxmb4z \
hello-world/micaz \
hello-world/minimal-net \
hello-world/native \
hello-world/sky \
hello-world/wismote \
hello-world/z1 \
eeprom-test/native \
collect/sky \
er-rest-example/wismote \
ipso-objects/wismote \
example-shell/native \
netperf/sky \
powertrace/sky \
rime/sky \
rime/z1 \
ravenusbstick/avr-ravenusb \
servreg-hack/sky \
sky/sky \
sky-ip/sky \
sky-shell/sky \
sky-shell-exec/sky \
sky-shell-webserver/sky \
tcp-socket/minimal-net \
telnet-server/minimal-net \
webserver/minimal-net \
webserver-ipv6/eval-adf7xxxmb4z \
wget/minimal-net \
zolertia/z1/z1 \
settings-example/avr-raven \
ipv6/multicast/sky \
sensniff/z1 \
cfs-coffee/sky \
cfs-coffee/z1 \
cfs-coffee/wismote \
cfs-coffee/avr-raven

TOOLS=

include ../Makefile.compile-test
