EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

ENFORCE_WARNING_COUNT = 1
# Format: example-path:target[:warning-count]
EXAMPLES = \
hello-world:avr-raven:6 \
hello-world:exp5438:8 \
hello-world:eval-adf7xxxmb4z:1 \
hello-world:micaz:6 \
hello-world:minimal-net:1 \
hello-world:native:5 \
hello-world:sky:5 \
hello-world:wismote:6 \
hello-world:z1:7 \
eeprom-test:native:6 \
collect:sky:21 \
er-rest-example:wismote:8 \
example-shell:native:54 \
netperf:sky:21 \
powertrace:sky:7 \
rime:sky:7 \
rime:z1:9 \
ravenusbstick:avr-ravenusb:11 \
servreg-hack:sky:6 \
sky:sky:4 \
sky-ip:sky:24 \
sky-shell:sky:21 \
sky-shell-exec:sky:21 \
sky-shell-webserver:sky:28 \
tcp-socket:minimal-net:3 \
telnet-server:minimal-net:40 \
webserver:minimal-net:3 \
webserver-ipv6:eval-adf7xxxmb4z:1 \
wget:minimal-net:9 \
z1:z1:25 \
settings-example:avr-raven:3 \
ipv6/multicast:sky:5 \

TOOLS=

include ../Makefile.compile-test
