# Platform Makefile

CLEAN += *.jn5168 
CLEAN += *.jn5168.bin
 
include $(CONTIKI)/platform/jn5168/Makefile.common

MODULES += core/net \
           core/net/mac \
           core/net/mac/tsch \
           core/net/llsec core/net/llsec/noncoresec 
           