EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
email/c64 \
ftp/c64 \
irc/c64 \
telnet-server/c64 \
wget/c64 \
webbrowser/c64 \
webbrowser/c128 \
webbrowser/atarixl \
webbrowser/apple2enh \
webserver/c64 \
webserver/c128 \
webserver/atarixl \
webserver/apple2enh \

TOOLS=

include ../Makefile.compile-test
