EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
email/c64 \
email/c128 \
email/atarixl \
email/apple2enh \
ftp/c64 \
ftp/c128 \
ftp/atarixl \
ftp/apple2enh \
irc/c64 \
irc/c128 \
irc/atarixl \
irc/apple2enh \
telnet-server/c64 \
telnet-server/c128 \
telnet-server/atarixl \
telnet-server/apple2enh \
webbrowser/c64 \
webbrowser/c128 \
webbrowser/atarixl \
webbrowser/apple2enh \
webserver/c64 \
webserver/c128 \
webserver/atarixl \
webserver/apple2enh \
wget/c64 \
wget/c128 \
wget/atarixl \
wget/apple2enh \

TOOLS=

include ../Makefile.compile-test
