EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
irc/c64 \
irc-80col/c64 \
telnet-server/c64 \
webbrowser/c64 \
webbrowser-80col/c64 \
webserver/c64:HTTPD-CFS=1 \
wget/c64 \
telnet-server/apple2enh \
telnet-server/atarixl \
telnet-server/c128 \
webbrowser-80col/apple2enh \
webbrowser-80col/atarixl \
webbrowser-80col/c128 \

TOOLS=

include ../Makefile.compile-test
