EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

ENFORCE_WARNING_COUNT = 1
# Format: example-path:target[:warning-count]
EXAMPLES = \
hello-world:minimal-net:1 \
hello-world:native:5 \
eeprom-test:native:6 \
example-shell:native:54 \
tcp-socket:minimal-net:3 \
telnet-server:minimal-net:40 \
webserver:minimal-net:3 \
wget:minimal-net:9 \

TOOLS=

include ../Makefile.compile-test
