EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/minimal-net \
hello-world/native \
eeprom-test/native \
example-shell/native \
tcp-socket/minimal-net \
telnet-server/minimal-net \
webserver/minimal-net \
wget/minimal-net \

TOOLS=

include ../Makefile.compile-test
