#
# Copyright (c) 2007, Adam Dunkels.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote
#    products derived from this software without specific prior
#    written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This file is part of the Contiki operating system.
#
# Author: Oliver Schmidt <ol.sc@web.de>
#
# $Id: Makefile.6502,v 1.35 2011/01/23 16:30:30 oliverschmidt Exp $
#

ifndef CC65_HOME
  ${error CC65_HOME not defined! You must specify where cc65 resides}
endif

all: cs8900a.eth lan91c96.eth

CONTIKI_TARGET_DIRS = . lib sys cfs
CONTIKI_CPU_DIRS    = . lib sys ctk net

CONTIKI_TARGET_SOURCEFILES += contiki-main.c
CONTIKI_CPU_SOURCEFILES    += log.c error.c unload.c config.c ctk-mouse.c \
                              clock.c mtarch.c mtarch-asm.S lc-asm.S \
                              uip_arch.c ethernet-drv.c ethernet.c

CONTIKI_SOURCEFILES += $(CTK) ctk-conio.c petsciiconv.c \
                       $(CONTIKI_TARGET_SOURCEFILES) $(CONTIKI_CPU_SOURCEFILES)
                       
TARGET_LIBFILES = $(TARGET).lib

ifdef ETHERNET
  CONTIKI_SOURCEFILES += $(ETHERNET)-eth.S
  CFLAGS += -DETHERNET=$(ETHERNET)
endif

### Compiler definitions

AS = ca65
CC = cc65
LD = ld65
AR = ar65

# Contiki is carefully designed to use extremely little stack.
# The apps coming with Contiki run even on a 0x100 byte stack.

ASFLAGS = -t $(TARGET)
CFLAGS += -t $(TARGET) -Or
LDFLAGS = -D __STACKSIZE__=0x200 -u _main -m contiki-$(TARGET).map
AROPTS  = a

### Compilation rules

.SUFFIXES:

CMD.EXE := $(shell echo)

CUSTOM_RULE_C_TO_OBJECTDIR_O = 1
$(OBJECTDIR)/%.o: %.c
	$(CC) $(CFLAGS) --create-dep $< -o $(@:.o=.s)
	@$(AS) $(ASFLAGS) $(@:.o=.s) -o $@
	@sed -e "s!.s:!.o:!" -e "s!\t! !" < $(@:.o=.u) > $(@:.o=.d)
	@rm -f $(@:.o=.s) $(@:.o=.u)
ifndef CMD.EXE
	@$(FINALIZE_DEPENDENCY)
endif

CUSTOM_RULE_C_TO_CO = 1
%.co: %.c
	$(CC) $(CFLAGS) -DAUTOSTART_ENABLE $< -o $(@:.co=.s)
	@$(AS) $(ASFLAGS) $(@:.co=.s) -o $@
	@rm -f $(@:.co=.s)

%.eth: $(OBJECTDIR)/%.o
	$(LD) -t module -m $@.map $< -o $@

ifdef ETHERNET
$(ETHERNET)-eth.S: $(ETHERNET).eth
	co65 --code-label _$(ETHERNET) -o $@ $<
endif
