CFLAGS += -DBOARD_SENSORTAG=1
CFLAGS += -DBACKDOOR_IOID=0x00000000

BOARD_SOURCEFILES += leds-arch.c sensortag-sensors.c  sensor-common.c
BOARD_SOURCEFILES += bmp-280-sensor.c tmp-007-sensor.c opt-3001-sensor.c
BOARD_SOURCEFILES += hdc-1000-sensor.c mpu-9250-sensor.c button-sensor.c
BOARD_SOURCEFILES += reed-relay.c ext-flash.c buzzer.c
BOARD_SOURCEFILES += board.c board-spi.c board-i2c.c
