CONTIKI_PROJECT = example-servreg-client
all: $(CONTIKI_PROJECT)

UIP_CONF_IPV6=1

APPS=servreg-hack
CONTIKI = ../..
include $(CONTIKI)/Makefile.include
-include /home/user/nes/testbed-scripts/Makefile.include

