CONTIKI_PROJECT = example-servreg-client
all: $(CONTIKI_PROJECT)

APPS=servreg-hack
CONTIKI = ../..
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
-include /home/user/nes/testbed-scripts/Makefile.include

