
;---------------------------------------------------------------------       
	.importzp       ptr1, ptr2, ptr3, ptr4, sreg
	.importzp	sp

	.import		_vnc_draw_datalen
	.import		_vnc_draw_dataptr
	.import		_vnc_draw_bitmapptr	
	.import		_vnc_draw_x
	.import		_vnc_draw_y
;---------------------------------------------------------------------
.bss
;---------------------------------------------------------------------
.data
;---------------------------------------------------------------------
.code
