contiki-collect-sky:
	(cd contiki-2.x/tools/collect-view/; ant dist && chmod 755 dist/tools/*-linux)
	cp -r contiki-2.x/tools/collect-view/dist contiki-collect-sky-$(RELEASE)

contiki-collect-sky-$(RELEASE).zip: contiki-collect-sky
	zip -r contiki-collect-sky-$(RELEASE).zip contiki-collect-sky-$(RELEASE)
	chmod 644 contiki-collect-sky-$(RELEASE).zip

BINARIES += contiki-collect-sky-$(RELEASE).zip
