EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/ev-aducrf101mkxz \
ipv6/rpl-border-router/ev-aducrf101mkxz \
webserver-ipv6/ev-aducrf101mkxz \
ipv6/multicast/ev-aducrf101mkxz \
cc2538dk/sniffer/ev-aducrf101mkxz \
hello-world/mulle \
ipv6/rpl-border-router/mulle \
webserver-ipv6/mulle \
ipv6/multicast/mulle \
er-rest-example/mulle \

TOOLS=

include ../Makefile.compile-test
