EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/ev-aducrf101mkxz \
ipv6/rpl-border-router/ev-aducrf101mkxz \
webserver-ipv6/ev-aducrf101mkxz \
ipv6/multicast/ev-aducrf101mkxz \
cc26xx/cc26xx-web-demo/srf06-cc26xx \
cc26xx/very-sleepy-demo/srf06-cc26xx:BOARD=sensortag/cc2650 \
cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=sensortag/cc2650 \
cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=srf06/cc13xx \
cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc2650 \
cc26xx/cc26xx-web-demo/srf06-cc26xx:BOARD=launchpad/cc1310 \
cc26xx/very-sleepy-demo/srf06-cc26xx \
hello-world/cc2538dk \
ipv6/rpl-border-router/cc2538dk \
ipv6/rpl-border-router/cc2538dk:MAKE_WITH_NON_STORING=1 \
er-rest-example/cc2538dk \
ipso-objects/cc2538dk \
webserver-ipv6/cc2538dk \
cc2538dk/cc2538dk \
cc2538dk/udp-ipv6-echo-server/cc2538dk \
ipv6/multicast/cc2538dk \
cc2538-common/cc2538dk \
cc2538-common/mqtt-demo/cc2538dk \
cc2538-common/crypto/cc2538dk \
cc2538-common/pka/cc2538dk \
cc2538-common/zoul \
cc2538-common/mqtt-demo/zoul \
cc2538-common/crypto/zoul \
cc2538-common/pka/zoul \
zolertia/zoul/zoul \
zolertia/zoul/cc1200-demo/zoul \
zolertia/zoul/orion/ip64-router/zoul:BOARD=orion \
openmote-cc2538/openmote-cc2538 \
er-rest-example/zoul \
ipso-objects/zoul \
hello-world/zoul \
er-rest-example/stm32nucleo-spirit1 \
ipv6/rpl-border-router/stm32nucleo-spirit1 \
ipv6/rpl-udp/stm32nucleo-spirit1 \
ipv6/simple-udp-rpl/stm32nucleo-spirit1 \
stm32nucleo-spirit1/sensor-demo/stm32nucleo-spirit1 \
ipv6/multicast/stm32nucleo-spirit1 \
udp-ipv6/stm32nucleo-spirit1 \
hello-world/stm32nucleo-spirit1 \
sensniff/cc2538dk \
sensniff/openmote-cc2538 \
sensniff/zoul \
sensniff/zoul:ZOUL_CONF_SUB_GHZ_SNIFFER=1 \
sensniff/srf06-cc26xx \
sensniff/srf06-cc26xx:BOARD=launchpad/cc1310 \
sensniff/ev-aducrf101mkxz \
cfs-coffee/cc2538dk \
cfs-coffee/openmote-cc2538 \
cfs-coffee/zoul \
fat/zoul:BOARD=remote-revb \
ipv6/rpl-tsch/zoul \
ipv6/rpl-tsch/zoul:MAKE_WITH_ORCHESTRA=1 \
ipv6/rpl-tsch/zoul:MAKE_WITH_SECURITY=1

TOOLS=

include ../Makefile.compile-test
