EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/ev-aducrf101mkxz \
ipv6/rpl-border-router/ev-aducrf101mkxz \
webserver-ipv6/ev-aducrf101mkxz \
ipv6/multicast/ev-aducrf101mkxz \
cc2538dk/sniffer/ev-aducrf101mkxz \
cc26xx/cc26xx-web-demo/srf06-cc26xx \
cc26xx/very-sleepy-demo/srf06-cc26xx \
hello-world/cc2538dk \
ipv6/rpl-border-router/cc2538dk \
er-rest-example/cc2538dk \
webserver-ipv6/cc2538dk \
cc2538dk/cc2538dk \
cc2538dk/udp-ipv6-echo-server/cc2538dk \
cc2538dk/sniffer/cc2538dk \
cc2538dk/mqtt-demo/cc2538dk \
cc2538dk/crypto/cc2538dk \
cc2538dk/pka/cc2538dk \
ipv6/multicast/cc2538dk \
zolertia/zoul/zoul \
zolertia/zoul/cc1200-demo/zoul \
er-rest-example/zoul \
hello-world/zoul \
cc2538dk/mqtt-demo/zoul \
er-rest-example/stm32nucleo-spirit1 \
ipv6/rpl-border-router/stm32nucleo-spirit1 \
ipv6/rpl-udp/stm32nucleo-spirit1 \
ipv6/simple-udp-rpl/stm32nucleo-spirit1 \
stm32nucleo-spirit1/sensor-demo/stm32nucleo-spirit1 \
ipv6/multicast/stm32nucleo-spirit1 \
udp-ipv6/stm32nucleo-spirit1 \
hello-world/stm32nucleo-spirit1 \

TOOLS=

include ../Makefile.compile-test
