CONTIKI=../../..
CONTIKI_PROJECT = node
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

TARGET ?= jn516x
JN516x_WITH_DR1175 = 1

CONTIKI_WITH_RIME = 1

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
