
;---------------------------------------------------------------------       
	.export		_cs8900a_rxtxreg
	.export		_cs8900a_txcmd
	.export		_cs8900a_txlen
	.export		_cs8900a_packetpp
	.export		_cs8900a_ppdata
	

;---------------------------------------------------------------------

	_cs8900a_rxtxreg	= $de08
	_cs8900a_txcmd		= $de0c
	_cs8900a_txlen		= $de0e
	_cs8900a_packetpp	= $de02
	_cs8900a_ppdata		= $de04

