#ifndef SCSI_COMMAND_H_SR3ALQCZSH__
#define SCSI_COMMAND_H_SR3ALQCZSH__

#define SCSI_CMD_CHANGE_DEFINITION		0x40
#define SCSI_CMD_COMPARE			0x39
#define SCSI_CMD_COPY				0x18
#define SCSI_CMD_COPY_AND_VERIFY		0x3a
#define SCSI_CMD_ERASE				0x19
#define SCSI_CMD_FORMAT				0x04
#define SCSI_CMD_INQUIRY			0x12
#define SCSI_CMD_LOAD_UNLOAD			0x1b
#define SCSI_CMD_LOCATE				0x2b
#define SCSI_CMD_LOCK_UNLOCK_CACHE		0x36
#define SCSI_CMD_LOG_SELECT			0x4c
#define SCSI_CMD_LOG_SENSE			0x4d
#define SCSI_CMD_MODE_SELECT_6			0x15
#define SCSI_CMD_MODE_SELECT_10			0x55
#define SCSI_CMD_MODE_SENSE_6			0x1a
#define SCSI_CMD_MODE_SENSE_10			0x5a
#define SCSI_CMD_PREFETCH			0x34
#define SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL	0x1e
#define SCSI_CMD_PRINT				0x0a
#define SCSI_CMD_READ_6				0x08
#define SCSI_CMD_READ_10			0x28
#define SCSI_CMD_READ_BLOCK_LIMITS		0x05
#define SCSI_CMD_READ_BUFFER			0x3c
#define SCSI_CMD_READ_CAPACITY			0x25
#define SCSI_CMD_READ_DEFECT_DATA		0x37
#define SCSI_CMD_READ_LONG			0x3e
#define SCSI_CMD_READ_POSITION			0x34
#define SCSI_CMD_READ_REVERSE			0x0f
#define SCSI_CMD_REASSIGN BLOCKS		0x07
#define SCSI_CMD_RECEIVE_DIAGNOSTIC_RESULTS	0x1c
#define SCSI_CMD_RECOVER_BUFFERED_DATA		0x14
#define SCSI_CMD_RELEASE_UNIT			0x17
#define SCSI_CMD_REQUEST_SENSE			0x03
#define SCSI_CMD_RESERVE_UNIT			0x16
#define SCSI_CMD_REWIND				0x01
#define SCSI_CMD_REZERO_UNIT			0x01
#define SCSI_CMD_SEARCH_DATA_EQUAL_10		0x31
#define SCSI_CMD_SEARCH_DATA_EQUAL_12		0xb1
#define SCSI_CMD_SEARCH_DATA_HIGH_10		0x30
#define SCSI_CMD_SEARCH_DATA_HIGH_12		0xb0
#define SCSI_CMD_SEARCH_DATA_LOW_10		0x32
#define SCSI_CMD_SEARCH_DATA_LOW_12		0xb2
#define SCSI_CMD_SEEK_6				0x0B
#define SCSI_CMD_SEEK_10			0x2B
#define SCSI_CMD_SEND_DIAGNOSTIC		0x1d
#define SCSI_CMD_SET_LIMITS			0x33
#define SCSI_CMD_SLEW_AND_PRINT			0x0b
#define SCSI_CMD_SPACE				0x11
#define SCSI_CMD_START_STOP_UNIT		0x1B
#define SCSI_CMD_STOP_PRINT			0x1b
#define SCSI_CMD_SYNCHRONIZE_CACHE		0x35
#define SCSI_CMD_SYNCHRONIZE_BUFFER		0x10
#define SCSI_CMD_TEST_UNIT_READY		0x00
#define SCSI_CMD_VERIFY				0x13
#define SCSI_CMD_WRITE_6			0x0a
#define SCSI_CMD_WRITE_10			0x2a
#define SCSI_CMD_WRITE_12			0xaa
#define SCSI_CMD_WRITE_AND_VERIFY_10		0x2e
#define SCSI_CMD_WRITE_AND_VERIFY_12		0xae
#define SCSI_CMD_WRITE_BUFFER			0x3b
#define SCSI_CMD_WRITE_FILEMARKS		0x10
#define SCSI_CMD_WRITE_LONG			0x3f
#define SCSI_CMD_WRITE_SAME			0x41



#endif /* SCSI_COMMAND_H_SR3ALQCZSH__ */
