# Common Makefile between Z1 and Z1SP

CONTIKI_TARGET_SOURCEFILES += contiki-z1-platform.c 
CLEAN += *.z1 

include $(CONTIKI)/platform/z1/Makefile.common

ifeq ($(ZOLERTIA_Z1SP),1)
include $(CONTIKI)/platform/z1/Makefile.z1sp
endif

MODULES += core/net \
           core/net/mac core/net/mac/contikimac \
           core/net/llsec \
           dev/cc2420
