# Common makefile between Z1 and Z1 Starter Platform

CONTIKI_TARGET_SOURCEFILES += contiki-z1-platform.c 
CLEAN += *.z1 

include $(CONTIKI)/platform/z1/Makefile.common

MODULES += core/net core/net/ip core/net/ipv6 core/net/ipv4 core/net/rpl \
           core/net/rime core/net/mac core/net/mac/contikimac \
           dev/cc2420 dev/sht11
