all: print-version hello-world
CONTIKI = ../../../..
APPS=serial-shell webserver telnetd

ifeq ($(TARGET), avr-raven)
  UIP_CONF_IPV6=1
endif

include $(CONTIKI)/Makefile.include
print-version:
	@$(CC) --version || echo
