EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/econotag \
hello-world/mbxxx:STM32W_CPUREV=CC \
ipv6/rpl-border-router/econotag \
er-rest-example/econotag \
webserver-ipv6/econotag \
ipv6/multicast/econotag \
econotag-flash-test/econotag \
econotag-ecc-test/econotag \

TOOLS=

include ../Makefile.compile-test
