EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/econotag \
hello-world/mbxxx \
ipv6/rpl-border-router/econotag \
er-rest-example/econotag \
webserver-ipv6/econotag \
ipv6/multicast/econotag \

TOOLS=

include ../Makefile.compile-test
