EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

ENFORCE_WARNING_COUNT = 1
# Format: example-path:target[:warning-count]
EXAMPLES = \
hello-world:econotag \
hello-world:mbxxx:9 \
ipv6/rpl-border-router:econotag \
er-rest-example:econotag \
webserver-ipv6:econotag \
ipv6/multicast:econotag \
econotag-flash-test:econotag \
econotag-ecc-test:econotag \

TOOLS=

include ../Makefile.compile-test
