EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

EXAMPLES = \
hello-world/econotag \
hello-world/mbxxx \
hello-world/cc2538dk \
ipv6/rpl-border-router/econotag \
ipv6/rpl-border-router/cc2538dk \
er-rest-example/econotag \
er-rest-example/cc2538dk \
webserver-ipv6/econotag \
webserver-ipv6/cc2538dk \
cc2538dk/cc2538dk \
cc2538dk/udp-ipv6-echo-server/cc2538dk \
cc2538dk/sniffer/cc2538dk \

TOOLS=

include ../Makefile.compile-test
