CONTIKI = ../..
ifndef TARGET
TARGET=netsim
endif
all: test-abc test-meshroute test-treeroute test-trickle test-uabc \
     test-rudolph0 test-rudolph1 test-rudolph2 test-rucb

include $(CONTIKI)/Makefile.include
