EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

# build jn516x examples, covering IPv6, RPL, CoAP, Rime, Nullrdc, Contikimac
EXAMPLES = \
hello-world/jn516x \
jn516x/dr1175-sensors/jn516x \
jn516x/rime/jn516x \
jn516x/rpl/border-router/jn516x \
jn516x/rpl/node/jn516x \
jn516x/rpl/coap-dongle-node/jn516x \
jn516x/rpl/coap-dr1175-node/jn516x \
jn516x/rpl/coap-dr1199-node/jn516x \
jn516x/tsch/simple-sensor-network/node/jn516x \
jn516x/tsch/simple-sensor-network/rpl-border-router/jn516x \
jn516x/tsch/tx-power-verification/node/jn516x \
jn516x/tsch/tx-power-verification/rpl-border-router/jn516x \
jn516x/tsch/uart1-test-node/jn516x \
ipv6/rpl-tsch/jn516x \
ipv6/rpl-tsch/jn516x:MAKE_WITH_ORCHESTRA=1 \
ipv6/rpl-tsch/jn516x:MAKE_WITH_SECURITY=1

TOOLS=

include ../Makefile.compile-test
