EXAMPLESDIR=../../examples
TOOLSDIR=../../tools

ENFORCE_WARNING_COUNT = 1
# Format: example-path:target[:warning-count]
EXAMPLES = \
jn516x/dr1175-sensors:jn516x \
jn516x/rime:jn516x \
jn516x/rpl/border-router:jn516x \
jn516x/rpl/node:jn516x \
jn516x/rpl/coap-dongle-node:jn516x:4 \
jn516x/rpl/coap-dr1175-node:jn516x:4 \
jn516x/rpl/coap-dr1199-node:jn516x:4

TOOLS=

include ../Makefile.compile-test
